services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "50150:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=PolygonApp;Username=myuser;Password=mypassword
    depends_on:
      - postgres
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: polygon-app/Dockerfile
      args:
        API_URL: http://backend:5000
    ports:
      - "80:80" 
    depends_on:
      - backend
    networks:
      - app-network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: PolygonApp        
      POSTGRES_USER: postgres          
      POSTGRES_PASSWORD: 1234  
    volumes:
      - postgres_data:/var/lib/postgresql/data  
    ports:
      - "5432:5432"  
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
