services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: PolygonApp        
      POSTGRES_USER: postgres          
      POSTGRES_PASSWORD: 1234  
    volumes:
      - postgres_data:/var/lib/postgresql/data  
    ports:
      - "54032:5432"
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
    - "5000:5000"  
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=PolygonApp;Username=postgres;Password=1234
    depends_on:
      - postgres
    networks:
      - app-network
    restart: always

  frontend:
    build:
      context: .
      dockerfile: polygon-app/Dockerfile
      args:
        API_URL: http://localhost:5000 
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
